#ifndef ANNA_STATUS_H
#define ANNA_STATUS_H

#define ANNA_STATUS_OK 0
#define ANNA_STATUS_PARSE_ERROR 127
#define ANNA_STATUS_MACRO_ERROR 126
#define ANNA_STATUS_INTERFACE_ERROR 125
#define ANNA_STATUS_TYPE_CALCULATION_ERROR 124
#define ANNA_STATUS_VALIDATION_ERROR 123
#define ANNA_STATUS_MODULE_SETUP_ERROR 122
#define ANNA_STATUS_ARGUMENT_ERROR 121
#define ANNA_STATUS_RUNTIME_ERROR 120
#define ANNA_STATUS_INTERNAL_ERROR 119

#endif
