#! /bin/bash

echo "
/*
  WARNING! This file is automatically generated by the make_anna_string_i.sh script.
  Do not edit it directly, your changes will be overwritten!
*/
"

init="

    anna_type_t *argv[]=
	{
	    string_type, string_type
	}
    ;
    
    wchar_t *argn[]=
	{
	  L\"this\", L\"value\"
	}
    ;

"

for i in "gt >" "lt <" "eq ==" "gte >=" "lte <=" "neq !="; do
    name=$(echo "$i"|cut -f 1 -d ' ')
    op=$(echo "$i"|cut -f 2 -d ' ')
    
    init="$init
    anna_native_method_create(
	string_type, -1, L\"__${name}__String__\", 0, 
	&anna_string_i_${name}, 
	string_type,
	2, argv, argn);
"

    echo "
static anna_object_t *anna_string_i_$name(anna_object_t **param)
{
    if(param[1]==null_object)
	return null_object;

    anna_string_t *str1 = as_unwrap(param[0]);
    anna_string_t *str2 = as_unwrap(param[1]);
    return (asi_compare(str1,str2) $op 0)?anna_int_one: null_object;    
}
"

done

init="$init
"

echo "
static void anna_string_type_i_create(anna_stack_template_t *stack)
{
$init
}
"

