#! /bin/bash

echo "
/*
  WARNING! This file is automatically generated by the make_anna_string_i.sh script.
  Do not edit it directly, your changes will be overwritten!
*/
"

init="
"

echo "
static void anna_string_type_i_create()
{
$init
}
"

