#! /bin/bash


echo "
/*
  WARNING! This file is automatically generated by the make_duck_int_i.sh script.
  Do not edit it directly, your changes will be overwritten!
*/
"

init="
    duck_type_t *c_argv[]=
	{
	    char_type, char_type
	}
    ;
    duck_type_t *i_argv[]=
	{
	    char_type, int_type
	}
    ;
    
    wchar_t *argn[]=
	{
	  L\"this\", L\"param\"
	}
    ;

"

for i in "gt >" "lt <" "eq ==" "gte >=" "lte <=" "neq !="; do
    name=$(echo "$i"|cut -f 1 -d ' ')
    op=$(echo "$i"|cut -f 2 -d ' ')
    
    init="$init
    duck_native_method_create(char_type, -1, L\"__${name}Char__\", 0, (duck_native_t)&duck_char_i_${name}, char_type, 2, c_argv, argn);"

    echo "
static duck_object_t *duck_char_i_$name(duck_object_t **param)
{
    if(param[1]==null_object)
        return null_object;
  
    wchar_t v1 = duck_char_get(param[0]);
    wchar_t v2 = duck_char_get(param[1]);
    return v1 $op v2?param[0]:null_object;
}
"

done

init="$init
"

for i in "add +" "sub -"; do
    name=$(echo "$i"|cut -f 1 -d ' ')
    op=$(echo "$i"|cut -f 2 -d ' ')
    
    init="$init
    duck_native_method_create(char_type, -1, L\"__${name}Int__\", 0, (duck_native_t)&duck_char_i_${name}, char_type, 2, i_argv, argn);"

    echo "
static duck_object_t *duck_char_i_$name(duck_object_t **param)
{
    if(param[1]==null_object)
        return null_object;
  
    wchar_t v1 = duck_char_get(param[0]);
    int v2 = duck_int_get(param[1]);
    return duck_char_create(v1 $op v2);
}
"
done

echo "
static void duck_char_type_i_create(duck_stack_frame_t *stack)
{
$init
}"

