#! /bin/bash

echo "
/*
  WARNING! This file is automatically generated by the make_anna_string_i.sh script.
  Do not edit it directly, your changes will be overwritten!
*/
"

init="

    anna_type_t *argv[]=
	{
	    string_type, string_type
	}
    ;
    
    wchar_t *argn[]=
	{
	  L\"this\", L\"value\"
	}
    ;

"

init="$init
"

echo "
static void anna_string_type_i_create(anna_stack_template_t *stack)
{
$init
}
"

