#! /bin/bash

echo "
/*
  WARNING! This file is automatically generated by the make_anna_object_i.sh script.
  Do not edit it directly, your changes will be overwritten!
*/
"

init="

    anna_type_t *argv[] = 
	{
	    object_type, object_type
	}
    ;
    
    wchar_t *argn[]=
	{
	    L\"this\", L\"other\"
	}
    ;
"

for i in "eq ==" "gt >" "lt <" "gte >=" "lte <=" "neq !="; do
    name=$(echo "$i"|cut -f 1 -d ' ')
    op=$(echo "$i"|cut -f 2- -d ' ')
    
    init="$init
    anna_native_method_create(
	object_type, -1, L\"__${name}__\", 0, 
	&anna_object_i_${name}, 
	int_type,
	2, argv, argn);

"

    echo "
static anna_object_t *anna_object_i_callback_$name(void *aux1, void *aux2, void *aux3, anna_object_t *res)
{
    wprintf(L\"Whoa, got a callback!!!!\n\");
    if(unlikely(res->type != int_type))
    {
	return null_object;
    }
    int res_int = anna_int_get(res);
    return res_int $op 0? anna_int_one:null_object;
}

static anna_object_t *anna_object_i_$name(anna_object_t **param)
{
    wprintf(L\"Weee, push a call\n\");
    anna_object_t *fun_object = *anna_static_member_addr_get_mid(param[0]->type, ANNA_MID_CMP);
    anna_vm_call_once(anna_object_i_callback_$name, 0, 0, 0, fun_object, 2, param);
    return 0;
}
"
done

echo "
static void anna_object_type_i_create()
{
$init
}
"

