
/*
  WARNING! This file is automatically generated by the make_anna_float_i.sh script.
  Do not edit it directly, your changes will be overwritten!
*/


static anna_vmstack_t *anna_float_i_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
    double v1 = anna_as_float(param[0]);
    double v2 = anna_as_float(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 + v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = anna_as_float(param[0]);
    double v2 = (double)anna_as_int(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 + v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_reverse_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = (double)anna_as_int(param[1]);
    double v2 = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 + v2);
    return stack;
}


static anna_vmstack_t *anna_float_i_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
    double v1 = anna_as_float(param[0]);
    double v2 = anna_as_float(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 + v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = anna_as_float(param[0]);
    double v2 = (double)anna_as_int(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 + v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_reverse_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = (double)anna_as_int(param[1]);
    double v2 = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 + v2);
    return stack;
}


static anna_vmstack_t *anna_float_i_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
    double v1 = anna_as_float(param[0]);
    double v2 = anna_as_float(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 - v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = anna_as_float(param[0]);
    double v2 = (double)anna_as_int(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 - v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_reverse_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = (double)anna_as_int(param[1]);
    double v2 = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 - v2);
    return stack;
}


static anna_vmstack_t *anna_float_i_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
    double v1 = anna_as_float(param[0]);
    double v2 = anna_as_float(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 - v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = anna_as_float(param[0]);
    double v2 = (double)anna_as_int(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 - v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_reverse_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = (double)anna_as_int(param[1]);
    double v2 = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 - v2);
    return stack;
}


static anna_vmstack_t *anna_float_i_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
    double v1 = anna_as_float(param[0]);
    double v2 = anna_as_float(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 * v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = anna_as_float(param[0]);
    double v2 = (double)anna_as_int(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 * v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_reverse_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = (double)anna_as_int(param[1]);
    double v2 = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 * v2);
    return stack;
}


static anna_vmstack_t *anna_float_i_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
    double v1 = anna_as_float(param[0]);
    double v2 = anna_as_float(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 / v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = anna_as_float(param[0]);
    double v2 = (double)anna_as_int(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 / v2);
    return stack;
}

static anna_vmstack_t *anna_float_i_int_reverse_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = (double)anna_as_int(param[1]);
    double v2 = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, v1 / v2);
    return stack;
}


static anna_vmstack_t *anna_float_i_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
    double v1 = anna_as_float(param[0]);
    double v2 = anna_as_float(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, pow(v1, v2));
    return stack;
}

static anna_vmstack_t *anna_float_i_int_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = anna_as_float(param[0]);
    double v2 = (double)anna_as_int(param[1]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, pow(v1, v2));
    return stack;
}

static anna_vmstack_t *anna_float_i_int_reverse_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    if(anna_is_obj(param[1]) && (anna_object_t *)param[1]==null_object)
    {
        anna_vmstack_drop(stack, 3);
        anna_vmstack_push_object(stack, null_object);
        return stack;
    }  
  
    double v1 = (double)anna_as_int(param[1]);
    double v2 = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_float(stack, pow(v1, v2));
    return stack;
}


static anna_vmstack_t *anna_float_i_abs(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    double v = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 2);
    anna_vmstack_push_float(stack, fabs(v));
    return stack;
}


static anna_vmstack_t *anna_float_i_neg(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    double v = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 2);
    anna_vmstack_push_float(stack, -v);
    return stack;
}


static anna_vmstack_t *anna_float_i_sign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    double v = anna_as_float(param[0]);
    anna_vmstack_drop(stack, 2);
    anna_vmstack_push_float(stack, (v==0.0?0.0:(v>0?1.0:-1.0)));
    return stack;
}


static void anna_float_type_i_create()
{

    anna_type_t *argv[]=
	{
	    float_type,
	    float_type
	}
    ;
    
    wchar_t *argn[]=
	{
	  L"this", L"param"
	}
    ;

    anna_type_t *i_argv[]=
	{
	    float_type,
	    int_type
	}
    ;
    
    wchar_t *i_argn[]=
	{
	  L"this", L"param"
	}
    ;

    mid_t mmid;
    anna_function_t *fun;


    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__add__Float__"), 0,
	&anna_float_i_add, 
	float_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__add__");

    mmid = anna_member_create_native_method(
        float_type, anna_mid_get(L"__add__Int__"), 0, 
	&anna_float_i_int_add, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__add__");

    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__add__IntReverse__"), 0, 
	&anna_float_i_int_reverse_add, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__add__");


    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__increaseAssign__Float__"), 0,
	&anna_float_i_increaseAssign, 
	float_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__increaseAssign__");

    mmid = anna_member_create_native_method(
        float_type, anna_mid_get(L"__increaseAssign__Int__"), 0, 
	&anna_float_i_int_increaseAssign, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__increaseAssign__");

    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__increaseAssign__IntReverse__"), 0, 
	&anna_float_i_int_reverse_increaseAssign, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__increaseAssign__");


    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__sub__Float__"), 0,
	&anna_float_i_sub, 
	float_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__sub__");

    mmid = anna_member_create_native_method(
        float_type, anna_mid_get(L"__sub__Int__"), 0, 
	&anna_float_i_int_sub, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__sub__");

    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__sub__IntReverse__"), 0, 
	&anna_float_i_int_reverse_sub, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__sub__");


    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__decreaseAssign__Float__"), 0,
	&anna_float_i_decreaseAssign, 
	float_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__decreaseAssign__");

    mmid = anna_member_create_native_method(
        float_type, anna_mid_get(L"__decreaseAssign__Int__"), 0, 
	&anna_float_i_int_decreaseAssign, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__decreaseAssign__");

    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__decreaseAssign__IntReverse__"), 0, 
	&anna_float_i_int_reverse_decreaseAssign, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__decreaseAssign__");


    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__mul__Float__"), 0,
	&anna_float_i_mul, 
	float_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__mul__");

    mmid = anna_member_create_native_method(
        float_type, anna_mid_get(L"__mul__Int__"), 0, 
	&anna_float_i_int_mul, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__mul__");

    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__mul__IntReverse__"), 0, 
	&anna_float_i_int_reverse_mul, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__mul__");


    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__div__Float__"), 0,
	&anna_float_i_div, 
	float_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__div__");

    mmid = anna_member_create_native_method(
        float_type, anna_mid_get(L"__div__Int__"), 0, 
	&anna_float_i_int_div, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__div__");

    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__div__IntReverse__"), 0, 
	&anna_float_i_int_reverse_div, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__div__");


    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__exp__Float__"), 0,
	&anna_float_i_exp, 
	float_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__exp__");

    mmid = anna_member_create_native_method(
        float_type, anna_mid_get(L"__exp__Int__"), 0, 
	&anna_float_i_int_exp, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_add(fun, L"__exp__");

    mmid = anna_member_create_native_method(
	float_type, anna_mid_get(L"__exp__IntReverse__"), 0, 
	&anna_float_i_int_reverse_exp, 
	float_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(float_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__exp__");



    anna_member_create_native_method(
	float_type, anna_mid_get(L"__abs__"), 0, 
	&anna_float_i_abs, 
	float_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	float_type, anna_mid_get(L"__neg__"), 0, 
	&anna_float_i_neg, 
	float_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	float_type, anna_mid_get(L"__sign__"), 0, 
	&anna_float_i_sign, 
	float_type,
	1, argv, argn, 0, 0);
}
