
/*
  WARNING! This file is automatically generated by the make_anna_complex_i.sh script.
  Do not edit it directly, your changes will be overwritten!
*/



static anna_vmstack_t *anna_complex_i_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = anna_as_complex(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_reverse_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_reverse_add(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}




static anna_vmstack_t *anna_complex_i_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = anna_as_complex(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_reverse_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_reverse_increaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 + v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}




static anna_vmstack_t *anna_complex_i_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = anna_as_complex(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_reverse_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_reverse_sub(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}




static anna_vmstack_t *anna_complex_i_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = anna_as_complex(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_reverse_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_reverse_decreaseAssign(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 - v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}




static anna_vmstack_t *anna_complex_i_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = anna_as_complex(param[1]);
        res = anna_complex_create(v1 * v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 * v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 * v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_reverse_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 * v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_reverse_mul(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 * v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}




static anna_vmstack_t *anna_complex_i_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = anna_as_complex(param[1]);
        res = anna_complex_create(v1 / v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 / v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 / v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_reverse_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(v1 / v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_reverse_div(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(v1 / v2);
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}




static anna_vmstack_t *anna_complex_i_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = anna_as_complex(param[1]);
        res = anna_complex_create(cpow(v1, v2));
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(cpow(v1, v2));
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v1 = anna_as_complex(param[0]);
        complex double v2 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(cpow(v1, v2));
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_int_reverse_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_int(param[1]);
        res = anna_complex_create(cpow(v1, v2));
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}

static anna_vmstack_t *anna_complex_i_float_reverse_exp(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 2;
    anna_object_t *res = null_object;
    if(likely(!anna_entry_null(param[1])))
    {  
        complex double v2 = anna_as_complex(param[0]);
        complex double v1 = (complex double)anna_as_float(param[1]);
        res = anna_complex_create(cpow(v1, v2));
    }
    anna_vmstack_drop(stack, 3);
    anna_vmstack_push_object(stack, res);
    return stack;
}



static anna_vmstack_t *anna_complex_i_neg(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);    
    anna_vmstack_drop(stack, 2); 
    anna_vmstack_push_object(stack, anna_complex_create(-v));
    return stack;
}


static anna_vmstack_t *anna_complex_i_sqrt(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);    
    anna_vmstack_drop(stack, 2); 
    anna_vmstack_push_object(stack, anna_complex_create(csqrt(v)));
    return stack;
}


static anna_vmstack_t *anna_complex_i_tan(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);    
    anna_vmstack_drop(stack, 2); 
    anna_vmstack_push_object(stack, anna_complex_create(ctan(v)));
    return stack;
}


static anna_vmstack_t *anna_complex_i_atan(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);    
    anna_vmstack_drop(stack, 2); 
    anna_vmstack_push_object(stack, anna_complex_create(catan(v)));
    return stack;
}


static anna_vmstack_t *anna_complex_i_sin(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);    
    anna_vmstack_drop(stack, 2); 
    anna_vmstack_push_object(stack, anna_complex_create(csin(v)));
    return stack;
}


static anna_vmstack_t *anna_complex_i_cos(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);    
    anna_vmstack_drop(stack, 2); 
    anna_vmstack_push_object(stack, anna_complex_create(ccos(v)));
    return stack;
}


static anna_vmstack_t *anna_complex_i_ln(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);    
    anna_vmstack_drop(stack, 2); 
    anna_vmstack_push_object(stack, anna_complex_create(clog(v)));
    return stack;
}


static anna_vmstack_t *anna_complex_i_abs(anna_vmstack_t *stack, anna_object_t *me)
{
    anna_entry_t **param = stack->top - 1;
    complex double v = anna_as_complex(param[0]);
    anna_vmstack_drop(stack, 2);
    anna_vmstack_push_entry(stack, anna_from_float(cabs(v)));
    return stack;
}


static void anna_complex_type_i_create()
{

    mid_t mmid;
    anna_function_t *fun;

    anna_type_t *argv[]=
	{
	    complex_type,
	    complex_type
	}
    ;
    
    wchar_t *argn[]=
	{
	  L"this", L"param"
	}
    ;

    anna_type_t *i_argv[]=
	{
	    complex_type,
	    int_type
	}
    ;
    
    wchar_t *i_argn[]=
	{
	  L"this", L"param"
	}
    ;

    anna_type_t *f_argv[]=
	{
	    complex_type,
	    float_type
	}
    ;
    
    wchar_t *f_argn[]=
	{
	  L"this", L"param"
	}
    ;




    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__add__Complex__"), 0,
	&anna_complex_i_add, 
	complex_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__add__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__add__Int__"), 0, 
	&anna_complex_i_int_add, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__add__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__add__Float__"), 0, 
	&anna_complex_i_float_add, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__add__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__add__IntReverse__"), 0, 
	&anna_complex_i_int_reverse_add, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__add__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__add__FloatReverse__"), 0, 
	&anna_complex_i_float_reverse_add, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__add__");



    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__increaseAssign__Complex__"), 0,
	&anna_complex_i_increaseAssign, 
	complex_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__increaseAssign__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__increaseAssign__Int__"), 0, 
	&anna_complex_i_int_increaseAssign, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__increaseAssign__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__increaseAssign__Float__"), 0, 
	&anna_complex_i_float_increaseAssign, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__increaseAssign__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__increaseAssign__IntReverse__"), 0, 
	&anna_complex_i_int_reverse_increaseAssign, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__increaseAssign__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__increaseAssign__FloatReverse__"), 0, 
	&anna_complex_i_float_reverse_increaseAssign, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__increaseAssign__");



    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__sub__Complex__"), 0,
	&anna_complex_i_sub, 
	complex_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__sub__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__sub__Int__"), 0, 
	&anna_complex_i_int_sub, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__sub__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__sub__Float__"), 0, 
	&anna_complex_i_float_sub, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__sub__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__sub__IntReverse__"), 0, 
	&anna_complex_i_int_reverse_sub, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__sub__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__sub__FloatReverse__"), 0, 
	&anna_complex_i_float_reverse_sub, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__sub__");



    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__decreaseAssign__Complex__"), 0,
	&anna_complex_i_decreaseAssign, 
	complex_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__decreaseAssign__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__decreaseAssign__Int__"), 0, 
	&anna_complex_i_int_decreaseAssign, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__decreaseAssign__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__decreaseAssign__Float__"), 0, 
	&anna_complex_i_float_decreaseAssign, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__decreaseAssign__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__decreaseAssign__IntReverse__"), 0, 
	&anna_complex_i_int_reverse_decreaseAssign, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__decreaseAssign__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__decreaseAssign__FloatReverse__"), 0, 
	&anna_complex_i_float_reverse_decreaseAssign, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__decreaseAssign__");



    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__mul__Complex__"), 0,
	&anna_complex_i_mul, 
	complex_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__mul__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__mul__Int__"), 0, 
	&anna_complex_i_int_mul, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__mul__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__mul__Float__"), 0, 
	&anna_complex_i_float_mul, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__mul__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__mul__IntReverse__"), 0, 
	&anna_complex_i_int_reverse_mul, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__mul__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__mul__FloatReverse__"), 0, 
	&anna_complex_i_float_reverse_mul, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__mul__");



    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__div__Complex__"), 0,
	&anna_complex_i_div, 
	complex_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__div__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__div__Int__"), 0, 
	&anna_complex_i_int_div, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__div__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__div__Float__"), 0, 
	&anna_complex_i_float_div, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__div__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__div__IntReverse__"), 0, 
	&anna_complex_i_int_reverse_div, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__div__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__div__FloatReverse__"), 0, 
	&anna_complex_i_float_reverse_div, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__div__");



    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__exp__Complex__"), 0,
	&anna_complex_i_exp, 
	complex_type,
	2, argv, argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__exp__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__exp__Int__"), 0, 
	&anna_complex_i_int_exp, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__exp__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__exp__Float__"), 0, 
	&anna_complex_i_float_exp, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_add(fun, L"__exp__");

    mmid = anna_member_create_native_method(
        complex_type, anna_mid_get(L"__exp__IntReverse__"), 0, 
	&anna_complex_i_int_reverse_exp, 
	complex_type,
	2, i_argv, i_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__exp__");

    mmid = anna_member_create_native_method(
	complex_type, anna_mid_get(L"__exp__FloatReverse__"), 0, 
	&anna_complex_i_float_reverse_exp, 
	complex_type,
	2, f_argv, f_argn, 0, 0);
    fun = anna_function_unwrap(anna_as_obj_fast(anna_entry_get_static(complex_type, mmid)));
    anna_function_alias_reverse_add(fun, L"__exp__");



    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__neg__"), 0, 
	&anna_complex_i_neg, 
	complex_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__sqrt__"), 0, 
	&anna_complex_i_sqrt, 
	complex_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__tan__"), 0, 
	&anna_complex_i_tan, 
	complex_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__atan__"), 0, 
	&anna_complex_i_atan, 
	complex_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__sin__"), 0, 
	&anna_complex_i_sin, 
	complex_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__cos__"), 0, 
	&anna_complex_i_cos, 
	complex_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__ln__"), 0, 
	&anna_complex_i_ln, 
	complex_type,
	1, argv, argn, 0, 0);
    anna_member_create_native_method(
	complex_type, anna_mid_get(L"__abs__"), 0, 
	&anna_complex_i_abs, 
	float_type,
	1, argv, argn, 0, 0);
}
